'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, MapPin, Phone, Plus, ShoppingBag, Sparkles, Star } from 'lucide-react'

type Product = { id: string; name: string; description: string; price: number; unit: string; sale_method?: 'piece' | 'weight'; price_per_kg?: number | null; category_id: string | null }
type Category = { id: string; name: string; slug: string }

const fallbackProducts: Product[] = [
  { id: 'pane-1', name: 'Pane Casereccio', description: 'Crosta croccante, mollica morbida e profumo di forno.', price: 3.5, unit: 'pezzo', category_id: 'pane' },
  { id: 'pane-2', name: 'Ciabatta', description: 'Leggera e alveolata, perfetta per ogni tavola.', price: 1.2, unit: 'pezzo', category_id: 'pane' },
  { id: 'focaccia-1', name: 'Focaccia Classica', description: 'Alta, soffice e finita con olio extravergine.', price: 4.5, unit: 'teglia', category_id: 'focacce' },
  { id: 'pane-3', name: 'Pane Integrale', description: 'Farina integrale macinata a pietra e semi tostati.', price: 3.8, unit: 'pezzo', category_id: 'pane' },
  { id: 'dolce-1', name: 'Cornetto', description: 'Sfogliato al burro, disponibile semplice o farcito.', price: 1.5, unit: 'pezzo', category_id: 'dolci' },
  { id: 'biscotti-1', name: 'Biscotti Artigianali', description: 'Piccola frolla dorata, fatta con burro e mandorle.', price: 5, unit: 'sacchetto', category_id: 'biscotteria' },
]
const fallbackCategories: Category[] = [{ id: 'pane', name: 'Pane', slug: 'pane' }, { id: 'focacce', name: 'Focacce', slug: 'focacce' }, { id: 'dolci', name: 'Dolci', slug: 'dolci' }, { id: 'biscotteria', name: 'Biscotteria', slug: 'biscotteria' }]

export function PanehubStorefront({ products = fallbackProducts, categories = fallbackCategories }: { products?: Product[]; categories?: Category[] }) {
  const [activeCategory, setActiveCategory] = useState('all')
  const [cart, setCart] = useState<Record<string, number>>({})
  const [showReservation, setShowReservation] = useState(false)
  const [submittedCode, setSubmittedCode] = useState('')
  const [form, setForm] = useState({ name: '', phone: '', email: '', date: '', slot: '07:00 – 09:00', notes: '' })
  const visible = activeCategory === 'all' ? products : products.filter((product) => product.category_id === activeCategory || product.category_id === categories.find((category) => category.slug === activeCategory)?.id)
  const cartItems = products.filter((product) => cart[product.id]).map((product) => ({ ...product, quantity: cart[product.id] }))
  const total = useMemo(() => cartItems.reduce((sum, item) => sum + (item.sale_method === 'weight' ? Number(item.price_per_kg ?? item.price) * item.quantity / 1000 : Number(item.price) * item.quantity), 0), [cartItems])
  const updateCart = (id: string, delta: number) => setCart((current) => { const product = products.find((item) => item.id === id); const step = product?.sale_method === 'weight' ? 100 : 1; return { ...current, [id]: Math.max(0, (current[id] ?? 0) + delta * step) } })
  const submitReservation = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!form.name || !form.phone || !form.date || cartItems.length === 0) return
    const response = await fetch('/api/reservations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.name, phone: form.phone, email: form.email || null, date: form.date, slot: form.slot, notes: form.notes || null, items: cartItems.map((item) => ({ productId: item.id.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i) ? item.id : null, productName: item.name, quantity: item.quantity, unitPrice: item.sale_method === 'weight' ? Number(item.price_per_kg ?? item.price) : Number(item.price), saleMethod: item.sale_method ?? 'piece' })) }) })
    const result = await response.json()
    if (!response.ok) { window.alert(result.error ?? 'Impossibile inviare la prenotazione.'); return }
    setSubmittedCode(result.code)
    setCart({})
  }
  return (
    <main className="min-h-screen bg-[#f7f1e8] text-[#30251f]">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10">
        <a href="#top" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#ad4e32] text-[#f7f1e8]"><Sparkles size={18} /></span><span className="font-serif text-xl font-semibold tracking-tight">Forno Panevero</span></a>
        <nav className="hidden items-center gap-8 text-sm font-medium text-[#76675c] md:flex"><a href="#forno" className="hover:text-[#ad4e32]">Il forno</a><a href="#catalogo" className="hover:text-[#ad4e32]">Catalogo</a><a href="#contatti" className="hover:text-[#ad4e32]">Contatti</a></nav>
        <button onClick={() => setShowReservation(true)} className="flex items-center gap-2 rounded-full bg-[#30251f] px-4 py-2.5 text-sm font-semibold text-[#f7f1e8] transition hover:bg-[#ad4e32]"><ShoppingBag size={16} /> Prenota ritiro</button>
      </header>
      <section id="top" className="mx-auto grid max-w-7xl gap-10 px-6 pb-16 pt-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pb-24 lg:pt-16">
        <div><p className="mb-6 flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-[#ad4e32]"><span className="h-px w-8 bg-[#ad4e32]" /> Milano · dal 1987</p><h1 className="max-w-3xl font-serif text-6xl leading-[.96] tracking-[-.04em] sm:text-7xl lg:text-8xl">Il pane buono<br /><em className="font-normal text-[#ad4e32]">sa di casa.</em></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#76675c]">Farine selezionate, lievitazioni lente e mani esperte. Ogni mattina sforniamo il meglio del forno italiano, per la tua tavola.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => document.getElementById('catalogo')?.scrollIntoView({ behavior: 'smooth' })} className="flex items-center gap-2 rounded-full bg-[#ad4e32] px-5 py-3 text-sm font-semibold text-[#fffaf3] hover:bg-[#8f3e28]">Scopri il catalogo <ArrowRight size={16} /></button><a href="#forno" className="rounded-full border border-[#d9cdbd] px-5 py-3 text-sm font-semibold text-[#5b4b41] hover:border-[#ad4e32]">La nostra storia</a></div></div>
        <div className="relative overflow-hidden rounded-[2rem] bg-[#c99a70] p-5 sm:p-8"><div className="aspect-[.88] overflow-hidden rounded-[1.5rem] bg-[#e5c3a0]" style={{ backgroundImage: 'radial-gradient(circle at 35% 24%, #f7e4c9 0 7%, transparent 7.5%), radial-gradient(circle at 64% 52%, #b86b43 0 14%, transparent 14.5%), linear-gradient(140deg, #f2d9b9, #b96842 70%, #6e382b)' }}><div className="flex h-full items-end p-7"><div className="max-w-[15rem] rounded-2xl bg-[#30251f]/90 p-5 text-[#fffaf3]"><p className="text-xs uppercase tracking-[.2em] text-[#e6c8a7]">Sfornato oggi</p><p className="mt-2 font-serif text-2xl">Pane, pazienza<br />e passione.</p></div></div></div><div className="absolute -bottom-2 -right-2 rounded-full bg-[#f7f1e8] px-5 py-3 text-sm font-semibold shadow-lg">100% artigianale</div></div>
      </section>
      <section id="catalogo" className="border-y border-[#dfd2c2] bg-[#fffaf3] px-6 py-16 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ad4e32]">Dalla vetrina alla tua tavola</p><h2 className="mt-3 font-serif text-5xl tracking-[-.03em]">Il catalogo</h2></div><div className="flex flex-wrap gap-2">{[{ id: 'all', name: 'Tutto' }, ...categories].map((category) => <button key={category.id} onClick={() => setActiveCategory(category.slug ?? category.id)} className={`rounded-full px-4 py-2 text-sm font-medium transition ${activeCategory === (category.slug ?? category.id) ? 'bg-[#30251f] text-[#fffaf3]' : 'bg-[#f1e8dc] text-[#76675c] hover:bg-[#e6d8c6]'}`}>{category.name}</button>)}</div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((product, index) => <article key={product.id} className="group rounded-2xl border border-[#e5d9ca] bg-[#f7f1e8] p-3 transition hover:-translate-y-1 hover:shadow-xl"><div className={`relative flex aspect-[1.2] items-end overflow-hidden rounded-xl p-5 ${index % 3 === 0 ? 'bg-[#d9a977]' : index % 3 === 1 ? 'bg-[#e8d0b0]' : 'bg-[#c78156]'}`}><div className="absolute inset-0 opacity-50" style={{ backgroundImage: 'radial-gradient(ellipse at 50% 70%, #8f4b2e 0 19%, transparent 20%), radial-gradient(ellipse at 38% 57%, #f2d4a9 0 11%, transparent 12%), radial-gradient(ellipse at 65% 42%, #f2d4a9 0 13%, transparent 14%)' }} /><span className="relative rounded-full bg-[#fffaf3]/85 px-3 py-1 text-xs font-semibold text-[#5b4b41]">{product.sale_method === 'weight' ? 'A peso · prezzo al kg' : `A ${product.unit}`}</span></div><div className="flex items-start justify-between gap-4 p-3 pb-2"><div><h3 className="font-serif text-2xl">{product.name}</h3><p className="mt-1 text-sm leading-5 text-[#76675c]">{product.description}</p></div><p className="shrink-0 font-semibold text-[#ad4e32]">€ {Number(product.sale_method === 'weight' ? (product.price_per_kg ?? product.price) : product.price).toFixed(2)}{product.sale_method === 'weight' ? ' / kg' : ''}</p></div><button onClick={() => updateCart(product.id, 1)} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-[#d9cdbd] py-2.5 text-sm font-semibold text-[#5b4b41] transition hover:border-[#ad4e32] hover:bg-[#ad4e32] hover:text-[#fffaf3]"><Plus size={16} /> Aggiungi</button></article>)}</div></div></section>
      <section id="forno" className="mx-auto grid max-w-7xl gap-10 px-6 py-16 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ad4e32]">Il forno</p><h2 className="mt-3 font-serif text-5xl tracking-[-.03em]">Una cosa semplice,<br /><em className="font-normal text-[#ad4e32]">fatta bene.</em></h2></div><div className="grid gap-7 text-[#76675c] sm:grid-cols-2"><p className="leading-7">Panevero nasce da una famiglia di fornai e da una convinzione: il tempo è l’ingrediente che non si può sostituire. Per questo impastiamo quando la città dorme e lasciamo che ogni pane trovi il suo ritmo.</p><p className="leading-7">Passa a trovarci per il profumo del mattino, oppure prenota il tuo ritiro: ti teniamo da parte quello che ami.</p></div></section>
      <footer id="contatti" className="bg-[#30251f] px-6 py-12 text-[#f7f1e8] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 md:flex-row"><div><p className="font-serif text-3xl">Forno Panevero</p><p className="mt-3 max-w-xs text-sm leading-6 text-[#c9b8a6]">Pane, focacce e dolci artigianali nel cuore di Milano.</p></div><div className="grid gap-3 text-sm text-[#c9b8a6]"><p className="flex items-center gap-2"><MapPin size={16} /> Via del Grano 12, Milano</p><p className="flex items-center gap-2"><Phone size={16} /> +39 02 555 0148</p><p className="flex items-center gap-2"><Star size={16} /> @fornopanevero</p></div></div></footer>
      {(cartItems.length > 0 || showReservation) && <aside className="fixed inset-x-4 bottom-4 z-20 mx-auto max-w-xl rounded-2xl border border-[#d9cdbd] bg-[#fffaf3] p-4 shadow-2xl"><div className="flex items-center justify-between"><div><p className="font-semibold">La tua prenotazione</p><p className="text-sm text-[#76675c]">{cartItems.reduce((sum, item) => sum + item.quantity, 0)} prodotti · € {total.toFixed(2)}</p></div><button onClick={() => setShowReservation(!showReservation)} className="flex items-center gap-2 rounded-full bg-[#ad4e32] px-4 py-2 text-sm font-semibold text-[#fffaf3]">{showReservation ? 'Chiudi' : 'Prenota ora'} <ChevronDown size={15} /></button></div>{showReservation && !submittedCode && <form onSubmit={submitReservation} className="mt-4 grid gap-3 border-t border-[#e5d9ca] pt-4 sm:grid-cols-2"><input required placeholder="Nome e cognome" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-xl border border-[#d9cdbd] bg-[#f7f1e8] px-3 py-2.5 text-sm outline-none focus:border-[#ad4e32]" /><input required placeholder="Telefono" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="rounded-xl border border-[#d9cdbd] bg-[#f7f1e8] px-3 py-2.5 text-sm outline-none focus:border-[#ad4e32]" /><input type="email" placeholder="Email (facoltativa)" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="rounded-xl border border-[#d9cdbd] bg-[#f7f1e8] px-3 py-2.5 text-sm outline-none focus:border-[#ad4e32]" /><input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} className="rounded-xl border border-[#d9cdbd] bg-[#f7f1e8] px-3 py-2.5 text-sm outline-none focus:border-[#ad4e32]" /><select value={form.slot} onChange={(e) => setForm({ ...form, slot: e.target.value })} className="rounded-xl border border-[#d9cdbd] bg-[#f7f1e8] px-3 py-2.5 text-sm outline-none focus:border-[#ad4e32]"><option>07:00 – 09:00</option><option>09:00 – 11:00</option><option>11:00 – 13:00</option><option>16:00 – 18:00</option></select><input placeholder="Note per il forno" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="rounded-xl border border-[#d9cdbd] bg-[#f7f1e8] px-3 py-2.5 text-sm outline-none focus:border-[#ad4e32]" /><button type="submit" className="flex items-center justify-center gap-2 rounded-xl bg-[#30251f] py-3 text-sm font-semibold text-[#fffaf3] sm:col-span-2">Conferma prenotazione <ArrowRight size={16} /></button></form>}{submittedCode && <div className="mt-4 flex items-center gap-3 border-t border-[#e5d9ca] pt-4 text-sm"><span className="grid size-8 place-items-center rounded-full bg-[#dce7d7] text-[#496044]"><Check size={16} /></span><p>Prenotazione ricevuta. Il tuo codice è <strong>{submittedCode}</strong>.</p></div>}</aside>}
    </main>
  )
}
