'use client'

import { useEffect, useState } from 'react'
import { ChevronDown, LockKeyhole, LogOut, Save } from 'lucide-react'

type Item = { product_name: string; quantity: number; subtotal: number }
type Order = { id: string; reservation_code: string; customer_name: string; customer_phone: string; pickup_date: string; pickup_time_slot: string; status: string; total: number; notes?: string; reservation_items: Item[] }

export default function DashboardPage() {
  const [verified, setVerified] = useState(false), [password, setPassword] = useState(''), [error, setError] = useState('')
  const [orders, setOrders] = useState<Order[]>([]), [expanded, setExpanded] = useState<string | null>(null), [busy, setBusy] = useState(false)
  const [current, setCurrent] = useState(''), [next, setNext] = useState(''), [message, setMessage] = useState('')
  async function loadOrders() { const response = await fetch('/api/dashboard/orders'); if (response.ok) setOrders(await response.json()) }
  useEffect(() => { if (document.cookie.includes('panehub_dashboard_verified=1')) { setVerified(true); loadOrders() } }, [])
  async function login(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); const response = await fetch('/api/dashboard/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); if (response.ok) { setVerified(true); loadOrders() } else setError((await response.json()).error ?? 'Accesso negato'); setBusy(false) }
  async function logout() { await fetch('/api/dashboard/auth', { method: 'DELETE' }); setVerified(false) }
  async function changePassword(event: React.FormEvent) { event.preventDefault(); setMessage(''); const response = await fetch('/api/dashboard/auth', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ currentPassword: current, newPassword: next }) }); setMessage(response.ok ? 'Password aggiornata. Effettua nuovamente l’accesso.' : ((await response.json()).error ?? 'Errore')); if (response.ok) setVerified(false) }
  if (!verified) return <main className="min-h-screen bg-background flex items-center justify-center p-6"><form onSubmit={login} className="w-full max-w-sm border border-border bg-card p-8 shadow-sm"><LockKeyhole className="text-primary mb-6"/><p className="font-mono text-xs uppercase tracking-[.2em] text-muted-foreground">PaneHub / Area riservata</p><h1 className="font-serif text-4xl mt-2">Bentornato.</h1><label className="block mt-8 text-sm font-medium">Password<input autoFocus required type="password" value={password} onChange={event => setPassword(event.target.value)} className="mt-2 w-full border border-border bg-background p-3 outline-none focus:border-primary" /></label>{error && <p className="mt-3 text-sm text-destructive">{error}</p>}<button disabled={busy} className="mt-6 w-full bg-primary text-primary-foreground p-3 font-medium">{busy ? 'Verifica…' : 'Accedi'}</button></form></main>
  return <main className="min-h-screen bg-background p-6 md:p-12"><header className="flex flex-wrap justify-between gap-4 border-b border-border pb-8"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-muted-foreground">PaneHub / Dashboard</p><h1 className="font-serif text-5xl mt-2">Ordini.</h1><p className="text-muted-foreground mt-2">Le prenotazioni ricevute dal sito.</p></div><button onClick={logout} className="flex h-fit items-center gap-2 border border-border px-4 py-2 text-sm"><LogOut size={16}/> Esci</button></header><section className="py-8"><div className="flex justify-between items-center mb-4"><h2 className="font-serif text-2xl">Prenotazioni recenti</h2><span className="font-mono text-xs text-muted-foreground">{orders.length} ORDINI</span></div>{orders.length === 0 ? <div className="border border-dashed border-border p-10 text-center text-muted-foreground">Nessuna ordinazione ricevuta.</div> : <div className="space-y-3">{orders.map(order => <article key={order.id} className="border border-border bg-card"><button onClick={() => setExpanded(expanded === order.id ? null : order.id)} className="w-full text-left p-5 flex justify-between gap-4"><div><p className="font-mono text-xs text-primary">{order.reservation_code}</p><h3 className="font-medium mt-1">{order.customer_name}</h3><p className="text-sm text-muted-foreground">{order.pickup_date} · {order.pickup_time_slot} · {order.customer_phone}</p></div><div className="text-right"><p className="font-medium">€ {Number(order.total).toFixed(2)}</p><span className="text-xs text-muted-foreground">{order.status}</span><ChevronDown size={16} className="ml-auto mt-2"/></div></button>{expanded === order.id && <div className="border-t border-border p-5 bg-muted/30"><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground mb-3">Dettaglio ordine</p>{order.reservation_items?.map((item, index) => <div key={index} className="flex justify-between text-sm py-1"><span>{item.quantity} × {item.product_name}</span><span>€ {Number(item.subtotal).toFixed(2)}</span></div>)}{order.notes && <p className="mt-4 text-sm text-muted-foreground">Note: {order.notes}</p>}</div>}</article>)}</div>}</section><section className="border-t border-border pt-8 max-w-lg"><h2 className="font-serif text-2xl mb-4">Impostazioni</h2><form onSubmit={changePassword} className="space-y-3"><input required type="password" placeholder="Password attuale" value={current} onChange={event => setCurrent(event.target.value)} className="w-full border border-border bg-background p-3"/><input required minLength={8} type="password" placeholder="Nuova password (min. 8 caratteri)" value={next} onChange={event => setNext(event.target.value)} className="w-full border border-border bg-background p-3"/><button className="flex items-center gap-2 border border-primary px-4 py-2"><Save size={16}/> Cambia password</button>{message && <p className="text-sm text-muted-foreground">{message}</p>}</form></section></main>
}
